### ISSUE TITLE
윈도우 설치 에러

### ISSUE THREAD

**Issue by JungCzoo** [kosslab-kr/rust#2]
<img width="406" alt="default" src="https://cloud.githubusercontent.com/assets/22129943/18807638/57ba4d40-8287-11e6-8cef-5419fbce7f37.PNG">

**Comment by sanxiyn** [comment]
이거 어떻게 해서 해결됐었죠?

**Comment by JungCzoo** [comment]
컴퓨터 재부팅 후 설치하니까 해결 됬습니다~
