### ISSUE TITLE
#25293 오래된 이슈 재현 실행 에러

### ISSUE THREAD

**Issue by chuck-park** [kosslab-kr/rust#7]
우선 저번에 설치할 때도 문제 있었던 v3가 또 문제 였던 것 같습니다.

![default](https://cloud.githubusercontent.com/assets/15935262/18960132/a4510516-86a3-11e6-8ad7-8d2f29402f74.JPG)

이런 식으로 rustc 실행을 차단해버려서 permission denied가 뜨고

이번엔 재부팅 한 뒤에 v3의 실시간 감시를 꺼도  
![2](https://cloud.githubusercontent.com/assets/15935262/18960188/eae25d36-86a3-11e6-813f-2f09d4851a0f.JPG)

이런 식으로 뜹니다. 

bench.rs 파일은 제가 직접 만드는건지 어디에 있는건지 모르겠어서

vim 을 사용하여 #25293 글에 올라온 코드
# ![feature(test)]

extern crate test;
use std::iter;
# [bench]

fn slow(b: &mut test::Bencher) {
    // This is dog-slow without optimizations...
    let s: String = iter::repeat("a").take(5_1024_1024).collect();
    println!("I made a string");
    b.iter(|| 1 + 1);
    b.bytes = s.len() as u64;
}

를 붙여넣고 종료한 뒤에 명령어 rustc --test bench.rs 를 입력했습니다.

![3](https://cloud.githubusercontent.com/assets/15935262/18960322/4af5ff20-86a4-11e6-8076-1f117b3e0f9a.JPG)

혹시 제가 파일을 잘못 만들었거나 실행 방법 등에서 오류가 있다면 말씀해주세요!

**Comment by chuck-park** [comment]
해당 이슈에 코멘트 했습니다.

**Comment by sanxiyn** [comment]
V3는 Rust 잘못이 아니니 어떻게 도와드릴 방법이 없구요.

`#[feature]` 에러는 stable 에서 실행해서 발생하는 에러입니다. 깜박하고 말씀을 못드렸는데, `rustup default nightly` 해서 nightly 로 업데이트하고 다시 해보세요.
